# Application properties
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8080
spring.application.name=Smart FinTech Solutions

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/
auth0.audience=${AUTH0_AUDIENCE}